export const mockAnalyticsSnapshots = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  return {
    id: `snap-${i}`,
    date: date.toISOString(),
    followers: 2400 + i * 12 + Math.floor(Math.random() * 20),
    followersGain: Math.floor(Math.random() * 15) + 3,
    impressions: Math.floor(Math.random() * 3000) + 1000,
    reach: Math.floor(Math.random() * 2000) + 800,
    clicks: Math.floor(Math.random() * 200) + 50,
    engagement: parseFloat((Math.random() * 5 + 1).toFixed(1)),
    reactions: Math.floor(Math.random() * 150) + 30,
    comments: Math.floor(Math.random() * 40) + 5,
    shares: Math.floor(Math.random() * 25) + 2,
  };
});

export const mockPosts = [
  {
    id: "post-1",
    title: "5 AI Trends Reshaping Business in 2026",
    content: "Artificial intelligence continues to transform how we work...",
    contentType: "thought_leadership",
    tone: "professional",
    hashtags: ["#AI", "#BusinessStrategy", "#Innovation"],
    keywords: ["AI", "business", "strategy"],
    status: "posted",
    scheduledAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    publishedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    mediaUrls: [],
    analytics: { impressions: 4520, clicks: 234, reactions: 89, comments: 23, shares: 15, reach: 3800, engagement: 3.8 },
  },
  {
    id: "post-2",
    title: "How We Scaled Our Team from 5 to 50",
    content: "Scaling a startup is never easy. Here's what I learned...",
    contentType: "long_post",
    tone: "friendly",
    hashtags: ["#Startup", "#Growth", "#Leadership"],
    keywords: ["startup", "scaling", "team"],
    status: "posted",
    scheduledAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    mediaUrls: [],
    analytics: { impressions: 8930, clicks: 567, reactions: 203, comments: 45, shares: 34, reach: 7200, engagement: 5.1 },
  },
  {
    id: "post-3",
    title: "Remote Work: The Data Behind Productivity",
    content: "We analyzed 6 months of data across our distributed team...",
    contentType: "educational",
    tone: "thought_leadership",
    hashtags: ["#RemoteWork", "#Productivity", "#Data"],
    keywords: ["remote work", "productivity"],
    status: "scheduled",
    scheduledAt: new Date(Date.now() + 86400000).toISOString(),
    publishedAt: null,
    mediaUrls: [],
    analytics: null,
  },
  {
    id: "post-4",
    title: "Join Our Engineering Team!",
    content: "We're hiring senior engineers to build the future of...",
    contentType: "hiring",
    tone: "friendly",
    hashtags: ["#Hiring", "#Engineering", "#Careers"],
    keywords: ["hiring", "engineering"],
    status: "draft",
    scheduledAt: null,
    publishedAt: null,
    mediaUrls: [],
    analytics: null,
  },
  {
    id: "post-5",
    title: "Customer Success Story: 300% ROI",
    content: "When Acme Corp started using our platform...",
    contentType: "case_study",
    tone: "sales",
    hashtags: ["#CaseStudy", "#ROI", "#Success"],
    keywords: ["case study", "ROI"],
    status: "posted",
    scheduledAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    publishedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    mediaUrls: [],
    analytics: { impressions: 3200, clicks: 178, reactions: 67, comments: 12, shares: 8, reach: 2900, engagement: 2.9 },
  },
  {
    id: "post-6",
    title: "The Future of LinkedIn Marketing",
    content: "LinkedIn's algorithm changes are creating new opportunities...",
    contentType: "educational",
    tone: "professional",
    hashtags: ["#LinkedIn", "#Marketing", "#SocialMedia"],
    keywords: ["linkedin", "marketing"],
    status: "scheduled",
    scheduledAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    publishedAt: null,
    mediaUrls: [],
    analytics: null,
  },
];

export const mockCampaigns = [
  {
    id: "camp-1",
    name: "Q2 Brand Awareness",
    status: "active",
    objective: "brand_awareness",
    budget: 5000,
    dailyBudget: 100,
    startDate: new Date(Date.now() - 86400000 * 15).toISOString(),
    endDate: new Date(Date.now() + 86400000 * 15).toISOString(),
    spend: 1523.45,
    impressions: 125000,
    clicks: 3420,
    ctr: 2.74,
    cpc: 0.45,
    cpm: 12.19,
    conversions: 89,
    leads: 34,
  },
  {
    id: "camp-2",
    name: "Product Launch Sponsored",
    status: "active",
    objective: "lead_generation",
    budget: 3000,
    dailyBudget: 75,
    startDate: new Date(Date.now() - 86400000 * 7).toISOString(),
    endDate: new Date(Date.now() + 86400000 * 23).toISOString(),
    spend: 487.20,
    impressions: 45000,
    clicks: 1230,
    ctr: 2.73,
    cpc: 0.40,
    cpm: 10.83,
    conversions: 42,
    leads: 18,
  },
  {
    id: "camp-3",
    name: "Hiring Campaign - Engineers",
    status: "paused",
    objective: "engagement",
    budget: 1500,
    dailyBudget: 50,
    startDate: new Date(Date.now() - 86400000 * 30).toISOString(),
    endDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    spend: 1500,
    impressions: 89000,
    clicks: 2100,
    ctr: 2.36,
    cpc: 0.71,
    cpm: 16.85,
    conversions: 28,
    leads: 12,
  },
  {
    id: "camp-4",
    name: "Thought Leadership Boost",
    status: "completed",
    objective: "brand_awareness",
    budget: 2000,
    dailyBudget: 80,
    startDate: new Date(Date.now() - 86400000 * 45).toISOString(),
    endDate: new Date(Date.now() - 86400000 * 20).toISOString(),
    spend: 2000,
    impressions: 210000,
    clicks: 5670,
    ctr: 2.7,
    cpc: 0.35,
    cpm: 9.52,
    conversions: 156,
    leads: 67,
  },
];

export const mockRecommendations = [
  { type: "timing", icon: "clock", title: "Best Time to Post", description: "Tuesday at 9:00 AM drives 2.3x more engagement than your average post.", priority: "high" },
  { type: "content", icon: "trending", title: "Carousel Posts Outperform", description: "Your carousel posts get 3.1x more impressions than text-only posts.", priority: "high" },
  { type: "hashtag", icon: "hash", title: "Top Hashtag Performance", description: "#AI and #Leadership are your top performing hashtags with 4.2% avg engagement.", priority: "medium" },
  { type: "growth", icon: "users", title: "Follower Growth Trend", description: "You're gaining 12 followers/day on average. Posting daily could increase this by 40%.", priority: "medium" },
  { type: "content", icon: "alert", title: "Underperforming Content", description: "Promotional posts get 60% less engagement. Try mixing in more educational content.", priority: "low" },
];

export const mockCalendarEvents = [
  ...mockPosts.filter(p => p.scheduledAt).map(p => ({
    id: p.id,
    title: p.title,
    date: p.scheduledAt!,
    status: p.status,
    contentType: p.contentType,
  })),
];
